server:
    port: 8888

spring:
  profiles:
    active: dev

---
spring:
  profiles: dev

logging:
  level:
    com.demo: debug

enviroment:
    name: Development

---
spring:
  profiles: prod

enviroment:
    name: Production
